/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/zHQoZw03fL1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function HeroSection() {
  return (
    (<div 
          className="flex items-center justify-center h-screen">
    <div className="flex flex-col h-[90vh] max-w-3xl mx-auto bg-background rounded-3xl shadow-lg overflow-hidden">
      <div className="bg-primary text-primary-foreground p-4">
        <h2 className="text-lg font-medium">Chatbot | AMERICAS BPS</h2>
      </div>
      <div className="flex-1 overflow-auto p-4">
        <div className="flex flex-col gap-4">
          <div className="flex items-start gap-3">
            <div
              className="rounded-full w-8 h-8 bg-primary text-primary-foreground flex items-center justify-center">
              <BotIcon className="w-5 h-5" />
            </div>
            <div className="bg-muted rounded-2xl p-3 max-w-[70%]">
              <p className="text-sm text-muted-foreground">
                ¡Hola! Soy un chatbot creado por Americas BPS. ¿En qué puedo asistirte hoy?
              </p>
            </div>
          </div>
          <div className="flex items-start gap-3 justify-end">
            <div className="bg-primary rounded-2xl p-3 max-w-[70%]">
              <p className="text-sm text-primary-foreground">
                Hola chat necesito ayuda para actualizar una información.
              </p>
            </div>
            <div
              className="rounded-full w-8 h-8 bg-[#55efc4] text-sm flex items-center justify-center">Tú</div>
          </div>
          <div className="flex items-start gap-3">
            <div
              className="rounded-full w-8 h-8 bg-primary text-primary-foreground flex items-center justify-center">
              <BotIcon className="w-5 h-5" />
            </div>
            <div className="bg-muted rounded-2xl p-3 max-w-[70%]">
              <p className="text-sm text-muted-foreground">
                ¡Claro! Cuentame en que necesitas mi ayuda?
              </p>
            </div>
          </div>
          <div className="flex items-start gap-3 justify-end">
            <div className="bg-primary rounded-2xl p-3 max-w-[70%]">
              <p className="text-sm text-primary-foreground">Necesito actualizar una información de unas computadoras, te voy a proporcionar los seriales.</p>
            </div>
            <div
              className="rounded-full w-8 h-8 bg-[#55efc4] text-sm flex items-center justify-center">Tú</div>
          </div>
          <div className="flex items-start gap-3">
            <div
              className="rounded-full w-8 h-8 bg-primary text-primary-foreground flex items-center justify-center">
              <BotIcon className="w-5 h-5" />
            </div>
            <div className="bg-muted rounded-2xl p-3 max-w-[70%]">
              <p className="text-sm text-muted-foreground">
                ¡Por supuesto! proporcioname las seriales de las computadoras
              </p>
            </div>
          </div>
          <div className="flex items-start gap-3 justify-end">
            <div className="bg-primary rounded-2xl p-3 max-w-[70%]">
              <p className="text-sm text-primary-foreground">Mira: Computadora N°1 serial 398765408, Computadora N°2 serial 874712689 y Computadora N°3 serial 912765408.</p>
            </div>
            <div
              className="rounded-full w-8 h-8 bg-[#55efc4] text-sm flex items-center justify-center">Tú</div>
          </div>
        </div>
      </div>
      <div className="bg-muted p-3 flex items-center gap-2">
        <Textarea
          placeholder="Escribe tu mensaje..."
          className="flex-1 rounded-2xl border-none focus:ring-0 resize-none"
          rows={1} />
        <Button
          variant="ghost"
          size="icon"
          className="rounded-full bg-primary text-primary-foreground hover:bg-primary/90">
          <SendIcon className="w-5 h-5" />
          <span className="sr-only">Enviar</span>
        </Button>
      </div>
    </div>
  </div>)
  );
}

function BotIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M12 8V4H8" />
      <rect width="16" height="12" x="4" y="8" rx="2" />
      <path d="M2 14h2" />
      <path d="M20 14h2" />
      <path d="M15 13v2" />
      <path d="M9 13v2" />
    </svg>)
  );
}


function SendIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>)
  );
}
