/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/bX2OAAngTCT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function InicioSesion() {
  return (
    (<div className="flex items-center justify-center h-screen bg-[#f0f4f8]">
      <div className="w-full max-w-md p-8 bg-white rounded-lg shadow-lg">
        <div className="mb-6 text-center">
          <h1 className="text-3xl font-bold text-[#1a5a40]">Bienvenido</h1>
          <p className="text-gray-500">Inicia sesión en tu cuenta</p>
        </div>
        <form>
          <div className="mb-4">
            <label
              htmlFor="username"
              className="block mb-2 text-sm font-medium text-[#1a5a40]">
              Nombre de usuario
            </label>
            <input
              type="text"
              id="username"
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-[#1a5a40] focus:border-[#1a5a40]"
              placeholder="Ingresa tu nombre de usuario" />
          </div>
          <div className="mb-6">
            <label
              htmlFor="password"
              className="block mb-2 text-sm font-medium text-[#1a5a40]">
              Contraseña
            </label>
            <input
              type="password"
              id="password"
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-[#1a5a40] focus:border-[#1a5a40]"
              placeholder="Ingresa tu contraseña" />
          </div>
          <div className="flex items-center justify-between mb-6">
            <button
              type="submit"
              className="px-4 py-2 font-medium text-white bg-[#1a5a40] rounded-md hover:bg-[#134432] focus:outline-none focus:ring-2 focus:ring-[#1a5a40] focus:ring-offset-2">
              Iniciar sesión
            </button>
            <a href="#" className="text-sm font-medium text-[#1a5a40] hover:underline">
              ¿Olvidaste tu contraseña?
            </a>
          </div>
        </form>
      </div>
    </div>)
  );
}
